---
title: "Reproducible Researach Project 1"
author: "Angela"
date: "24/02/2021"
output:
  html_document: default
  pdf_document: default
---

knitr::opts_chunk$set(warning=FALSE)

######loading and processing data
library(ggplot2)
activity <- read_csv("C:/Users/Cate Afeeva/Downloads/repdata_data_activity.zip")
activity$date <- as.POSIXct(activity$date, "%Y-%m-%d")
weekday <- weekdays(activity$date)
activity <- cbind(activity,weekday)
summary(activity)

##What is mean total number of steps taken per day?
######total number of steps taken per day
total_steps <- with(activity, aggregate(steps, by = list(date), FUN = sum, na.rm = TRUE))
names(total_steps) <- c("date", "steps")
######histogram of the total number of steps taken each day
hist(total_steps$steps, main = "Total number of steps taken per day", xlab = "Total steps taken per day", col = "darkblue", ylim = c(0,20), breaks = seq(0,25000, by=2500))
######mean of the total number of steps taken per day
mean(total_steps$steps)
######median of the total number of steps taken per day
median(total_steps$steps)

##What is the average daily activity pattern?
##5-minute interval and the average number of steps taken, averaged across all days
average_daily_activity <- aggregate(activity$steps, by=list(activity$interval), FUN=mean, na.rm=TRUE)
names(average_daily_activity) <- c("interval", "mean")
######plot time series
plot(average_daily_activity$interval, average_daily_activity$mean, type = "l", col="darkblue", lwd = 2, xlab="Interval", ylab="Average number of steps", main="Average number of steps per intervals")
######interval which contains the maximum number of steps on average across all the days in the dataset
average_daily_activity[which.max(average_daily_activity$mean), ]$interval

##Imputing missing values
######total number of missing values in the dataset
sum(is.na(activity$steps))
######filling in all of the missing values in the dataset
imputed_steps <- average_daily_activity$mean[match(activity$interval, average_daily_activity$interval)]
######Create a new dataset that is equal to the original dataset but with the missing data filled in
activity_imputed <- transform(activity, steps = ifelse(is.na(activity$steps), yes = imputed_steps, no = activity$steps))
total_steps_imputed <- aggregate(steps ~ date, activity_imputed, sum)
names(total_steps_imputed) <- c("date", "daily_steps")
######Plot histogram of the total number of steps taken each day
hist(total_steps_imputed$daily_steps, col = "darkblue", xlab = "Total steps per day", ylim = c(0,30), main = "Total number of steps taken each day", breaks = seq(0,25000,by=2500))
######Mean of the total number of steps taken per day
mean(total_steps_imputed$daily_steps)
######Median of the total number of steps taken per day
median(total_steps_imputed$daily_steps)

##Are there differences in activity patterns between weekdays and weekends?
######Create a new factor variable in the dataset with two levels
activity$date <- as.Date(strptime(activity$date, format="%Y-%m-%d"))
activity$datetype <- sapply(activity$date, function(x) {
  if (weekdays(x) == "Saturday" | weekdays(x) =="Sunday") 
  {y <- "weekend"} else 
  {y <- "weekday"}
  y
})
######Create panel plot containing a time series plot
activity_by_date <- aggregate(steps~interval + datetype, activity, mean, na.rm = TRUE)
plot<- ggplot(activity_by_date, aes(x = interval , y = steps, color = datetype)) +
  geom_line() +
  labs(title = "Average daily steps by type of date", x = "Interval", y = "Average number of steps") +
  facet_wrap(~datetype, ncol = 1, nrow=2)
print(plot)





